platform :ios, '7.0'
pod 'SDWebImage', '~>3.7'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'MMDrawerController', '~> 0.5.7'
pod 'SDAutoLayout', '~> 1.31'
pod 'MJExtension', '~> 3.0.10'
pod 'AFNetworking', '~> 2.5.0'
pod 'YYCache', '~> 1.0'
