platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
platform :ios, '8.0'
pod 'IQKeyboardManager'
platform :ios, '8.0'
pod 'MBProgressHUD', '~> 0.9.2'
platform :ios, '8.0'
pod 'MMDrawerController', '~> 0.5.7'
platform :ios, '8.0'
pod 'SDAutoLayout', '~> 1.31'
